### ISSUE TITLE
Will you ever upgrade to a newer version of Guzzle?

### ISSUE THREAD

**Issue by FASNASTIC** [fusonic/opengraph#15]
I feel uncomfortable using your package with such an old version of Guzzle.
I believe it is insecure these days.
Is your project still active enough to make this upgrade?
Many thanks!

**Comment by daveybrown** [comment]
The old version of Guzzle used deprecated code, and isn't compatible with php 7.1. I get the error `HP Fatal error:  Cannot use lexical variable $eventName as a parameter name in /vendor/guzzlehttp/guzzle/src/Event/Emitter.php on line 49
`

**Comment by daveybrown** [comment]
The project seems compatible with guzzle 6.x, for a quick fix replace 

```
{
    "require": {
        "fusonic/opengraph": "@dev"
    }
}
```

with 

```
{
    "require": {
        "fusonic/opengraph": "@dev",
        "guzzlehttp/guzzle": "6.3 as 4.0"
    }
}
```

In the root composer.json, then  run `php composer.phar update`

**Comment by mpyw** [comment]
[mpyw/opengraph: A simple PHP library to read Open Graph data from the web or publish your own resources.](https://github.com/mpyw/opengraph)

My forked implementation does not depend on Guzzle.

**Comment by jrodwell** [comment]
> The project seems compatible with guzzle 6.x, for a quick fix replace
> 
> ```
> {
>     "require": {
>         "fusonic/opengraph": "@dev"
>     }
> }
> ```
> 
> with
> 
> ```
> {
>     "require": {
>         "fusonic/opengraph": "@dev",
>         "guzzlehttp/guzzle": "6.3 as 4.0"
>     }
> }
> ```
> 
> In the root composer.json, then run `php composer.phar update`

Thank you! Tried resolving this by changing the version in the composer.json in fusonic/opengraph, and then by requiring Guzzle ^6.0 in the root of my project, but neither worked. I was not aware of the 'as' keyword. I figured since it requires ^4.0 (greater than 4.0) it would work with 6.0 without 'as' but apparently not. If anyone can explain why I'd appreciate it.

Devs please update this package as it does not work with php 7.2...
