### ISSUE TITLE
httpRequestFactory?

### ISSUE THREAD

**Issue by jenstornell** [fusonic/opengraph#31]
With help from another issue I figured out the `$httpClient`.

>Notice: Undefined variable: httpRequestFactory

**How can I make `$httpRequestFactory` not undefined?**

```php
<?php
use Fusonic\OpenGraph\Consumer;
use Symfony\Component\HttpClient\NativeHttpClient;
use Symfony\Component\HttpClient\Psr18Client;

require "vendor/autoload.php";

$httpClient = new Psr18Client(new NativeHttpClient([ "headers" => [ "User-Agent" => "facebookexternalhit/1.1" ] ]));
$consumer = new Consumer($httpClient, $httpRequestFactory);
$object = $consumer->loadUrl("http://www.youtube.com/watch?v=P422jZg50X4");

print_r($object);
```

**Comment by mburtscher** [comment]
Hello @jenstornell, as you can see [in the example](https://github.com/fusonic/opengraph/blob/master/examples/consume_website.php) you can pass the `$httpClient` as a second argument in this case since Symfony's `Psr18Client` also implements the `RequestFactoryInterface`.

Please don't hesitate to re-open the issue in case this doesn't help.
